    
    // An array with the tag array names

let tagArrays = [
    "drinks",
    "sweets_snacks",
    "baked_goods_pastry",
    "grains_pasta",
    "fruits_vegetables",
    "meat_dairy",
    "vege_vegan",
    "ready_meals",
    "semi_finished",
    "sauces_spices",
    "other"
];

    // The tag arrays 
    // holy fuck I've spent fuck knows how long on this shit

// .ß for not displaying in the tag list on the product page
let drinksLabels = [
    "--group--Grupy",
    "Alkohol",
    "Cola",
    "Energetyki",
    "Herbata",
    "Kawa",
    "Smoothie",
    "Sok",
    "Woda",
    
    "--group--Właściwości",
    "Gazowane",
    "Niegazowane",
    "Ciepłe",
    "Zimne",
    "Ma kalorie",
    "Bez kalorii",
    "Z kofeiną",
    "Bez kofeiny",
    
    "--group--Smak",
    "Gorzkie",
    "Kwaśne",
    "Słodkie",
    "Czekoladowe",
    "Kakaowe",
    "Karmelowe",
    "Kawowe",
    "Kokosowe",
    "Miętowe",
    "Orzechowe",
    "Owocowe",
    "Śmietankowe",
    "Waniliowe",
    "Warzywne"
];
let drinksList = [
    "--group--",
    "alkohol, alkoholowe.ß, alkoholowy.ß, alkoholowa.ß",
    "cola, colowy, kolowy.ß",
    "energetyki, napój energetyczny, napoj energetyczny, energy drink",
    "herbata, herbaciany, herbaciana.ß, tea",
    "kawa, kawowe, kawowy.ß, kawowa.ß, coffee",
    "smoothie, koktail.ß, cocktail",
    "sok, soczek.ß",
    "woda",
    
    "--group--",
    "gazowane, gazowany.ß, gazowana.ß, musujące, musujace, musujący, musujacy.ß, musująca, musujaca.ß, z gazem",
    "niegazowane, niegazowany.ß, niegazowana.ß, bez gazu",
    "ciepłe, cieple, ciepły, cieply.ß, ciepła, ciepla.ß, na ciepło, na cieplo, gorące, gorace, gorący, goracy.ß, gorąca, goraca.ß",
    "zimne, zimny.ß, zimna.ß, na zimno, ice, iced, mrożone, mrozone.ß, morożony, mrozony.ß, mrożona, mrozona.ß",
    "ma kalorie, kaloryczne, kaloryczny.ß, kaloryczna.ß, z kaloriami",
    "bez kalorii, niekaloryczne, low-kcal, low kcal.ß, zero, bez cukru",
    "z kofeiną, z kofeina, caffeine, kofeina",
    "bez kofeiny",
    
    "--group--",
    "gorzkie, gorzki.ß, gorzka.ß",
    "kwaśne, kwasne, kwaśny, kwasny.ß, kwaśna, kwasna.ß",
    "słodkie, slodkie.ß, słodka, slodka.ß",
    "czekoladowe, czekoladowy, czekoladowa",
    "kakaowe, kakaowy.ß, kakaowa.ß",
    "karmelowe, karmelowy.ß, karmelowa.ß",
    "kawowe, kawowy.ß, kawowa.ß, coffee",
    "kokosowe, kokosowy.ß, kokosowa.ß",
    "miętowe, mietowe, miętowy, mietowy.ß, miętowa, mietowa.ß, mięta, mieta, peppermint.ß",
    "orzechowe, orzechowy.ß, orzechowa.ß, nut.ß",
    "owocowe, owocowy.ß, owocowa.ß",
    "śmietankowe, smietankowe, śmietankowy, smietankowy.ß, śmietankowa, smietankowa.ß",
    "waniliowe, wianiliowy.ß, waniliowa.ß",
    "warzywne, warzywny.ß, warzywna.ß"
];

let sweets_snacksLabels = [
    "--group--Grupy",
    "Przekąski",
    "Słodycze",
    
    "--group--Przekąski",
    "Chipsy",
    "Chrupki",
    "Krakersy",
    "Nachos",
    "Orzeszki",
    "Popcorn",
    "Prażynki",
    "Suchary",
    
    "--group--Słodycze",
    "Batony",
    "Ciastka",
    "Cukierki",
    "Czekolada",
    "Galaretki",
    "Guma",
    "Lizaki",
    "Lody",
    "Pianki",
    "Sorbety",
    "Wafelki",
    "Żelki",
    
    "--group--Właściwości",
    "Low-kcal",
    "High-kcal",
    "Low-carb",
    "High-carb",
    
    "--group--Smak",
    "Gorzkie",
    "Kwaśne",
    "Ostre",
    "Słodkie",
    "Słone",
    "Cebulowe",
    "Fromage",
    "Mięsne",
    "Paprykowe",
    "Serowe",
    "Solone",
    "Alkoholowe",
    "Czekoladowe",
    "Kakaowe",
    "Karmelowe",
    "Kawowe",
    "Kokosowe",
    "Miętowe",
    "Mleczne",
    "Orzechowe",
    "Owocowe",
    "Śmietankowe",
    "Waniliowe"
];
let sweets_snacksList = [
    "--group--",
    "przekąski, przekaski, snacks.ß",
    "słodycze, slodycze, słodkości, slodkosci.ß",
    
    "--group--",
    "chipsy, czipsy.ß",
    "chrupki",
    "krakersy",
    "nachos, naczosy.ß",
    "orzeszki, orzechy.ß",
    "popcorn",
    "prażynki, prazynki",
    "suchary, sucharki.ß",
    
    "--group--",
    "batony, batoniki.ß",
    "ciastka, ciasteczka.ß",
    "cukierki",
    "czekolada, czekoladki.ß",
    "galaretki",
    "guma, rozpuszczalna.ß",
    "lizaki",
    "lody, lód, lod.ß",
    "pianki, pianka.ß",
    "sorbety",
    "wafelki, wafelek.ß",
    "żelki, zelki",
    
    "--group--",
    "low-kcal, low kcal.ß, niskokaloryczne, nisko kaloryczne.ß, diet.ß",
    "high-kcal, high kcal, wysokokaloryczne, wysoko kaloryczne.ß",
    "low-carb, low carb.ß, mało węglowodanów, malo weglowodanow, mało węgli, malo wegli.ß",
    "high-carb, high carb.ß, dużo węglowodanów, duzo weglowodanow, dużo węgli, duzo wegli.ß",
    
    "--group--",
    "gorzkie, gorzki.ß, gorzka.ß",
    "kwaśne, kwasne, kwaśny, kwasny.ß, kwaśna, kwasna.ß",
    "ostre, ostry.ß, ostra.ß, piknatne, pikantny.ß, pikantna.ß",
    "słodkie, slodkie.ß, słodka, slodka.ß",
    "słone, slone, słony, slony.ß, słona, slona.ß",
    "cebulowe, zielona cebulka, green onion",
    "fromage",
    "mięsne, miesne",
    "paprykowe, papryka",
    "serowe",
    "solone, sól, soli.ß",
    "alkoholowe, alkohol",
    "czekoladowe, czekoladowy, czekoladowa",
    "kakaowe, kakaowy.ß, kakaowa.ß",
    "karmelowe, karmelowy.ß, karmelowa.ß",
    "kawowe, kawowy.ß, kawowa.ß, coffee",
    "kokosowe, kokosowy.ß, kokosowa.ß",
    "miętowe, mietowe, miętowy, mietowy.ß, miętowa, mietowa.ß, mięta, mieta, peppermint.ß",
    "mleczne, mleczny.ß, mleczna.ß, mleko",
    "orzechowe, orzechowy.ß, orzechowa.ß, nut.ß",
    "owocowe, owocowy.ß, owocowa.ß",
    "śmietankowe, smietankowe, śmietankowy, smietankowy.ß, śmietankowa, smietankowa.ß",
    "waniliowe, wianiliowy.ß, waniliowa.ß"
];

let baked_goods_pastryLabels = [
    "--group--Grupy",
    "Pieczywo",
    "Wyr. cukier.",
    
    "--group--Pieczywo",
    "Bagietki",
    "Bułki",
    "Chleb",
    "Pita",
    "Rogaliki",
    "Tortilla",
    
    "--group--Wyr. cukier.",
    "Babeczki",
    "Biszkopty",
    "Ciasta",
    "Ciastka",
    "Drożdżówki",
    "Eklery",
    "Makaroniki",
    "Muffinki",
    "Omlety",
    "Placki",
    "Praliny",
    "Ptysie",
    "Pączki",
    "Torty",
        
    "--subgroup--Dodatki",
    "Z nadzieniem",
    "Z budyniem",
    "Z dżemem",
    "Z orzechami",
    "Z owocami",
    "Z serem",
    
    "--group--Właściwości",
    "Low-kcal",
    "High-kcal",
    "Low-carb",
    "High-carb",
    "Jasne",
    "Ciemne",
    "Pełnoziarniste",
    
    "--group--Smak",
    "Słodkie",
    "Słone",
    "Alkoholowe",
    "Czekoladowe",
    "Kakaowe",
    "Karmelowe",
    "Kawowe",
    "Kokosowe",
    "Miętowe",
    "Orzechowe",
    "Owocowe",
    "Śmietankowe",
    "Waniliowe"
];
let baked_goods_pastryList = [
    "--group--",
    "pieczywo, wypieki",
    "wyroby cukiernicze",
    
    "--group--",
    "bagietki, bagietka.ß, baguette.ß",
    "bułki, bulka, bułka, bulka.ß, bułeczki, buleczki.ß, bułeczka, buleczka.ß",
    "chleb",
    "pita, pity.ß, flatbread, flat bread.ß",
    "rogaliki, rogalik.ß",
    "tortilla, wrap",
    
    "--group--",
    "babeczki, babeczka.ß, cupcake",
    "biszkopty, biszkopt",
    "ciasta, ciasto.ß",
    "ciastka, ciastko.ß, ciasteczka.ß, ciasteczko.ß",
    "drożdżówki, drozdzowki, drożdżówka, drozdzowka.ß",
    "eklery, eklerki, eklerek.ß",
    "makaroniki, macarons",
    "muffinki, muffiny.ß",
    "omlety",
    "placki, placek.ß, tarty, tarta.ß",
    "praliny, pralinki.ß, pralina.ß, pralinka.ß",
    "ptysie, ptyś, ptys.ß",
    "pączki, paczki, pączek, paczek.ß, doughnut",
    "torty, urodziny.ß, urodzinowe.ß",
    
    "--group--",
    "z nadzieniem, nadziewane, nadziewany.ß, nadziewana.ß",
    "z budyniem, budyń, budyn",
    "z dżemem, z dzemem, dżem, dzem",
    "z orzechami, orzechy",
    "z owocami, owoce",
    "z serem, ser, serowe.ß, serowy.ß, serowa.ß",
    
    "--group--",
    "low-kcal, low kcal.ß, niskokaloryczne, nisko kaloryczne.ß, diet.ß",
    "high-kcal, high kcal, wysokokaloryczne, wysoko kaloryczne.ß",
    "low-carb, low carb.ß, mało węglowodanów, malo weglowodanow, mało węgli, malo wegli.ß",
    "high-carb, high carb.ß, dużo węglowodanów, duzo weglowodanow, dużo węgli, duzo wegli.ß",
    "jasne, jasny.ß, jasna.ß",
    "ciemne, ciemny.ß, ciemna.ß",
    "pełnoziarniste, pelnoziarniste, pełnoziarnisty, pelnoziarnisty.ß, pełnoziarnista, pelnoziarnista.ß",
    
    "--group--",
    "słodkie, slodkie.ß, słodka, slodka.ß",
    "słone, slone, słony, slony.ß, słona, slona.ß",
    "alkoholowe, alkohol",
    "czekoladowe, czekoladowy, czekoladowa",
    "kakaowe, kakaowy.ß, kakaowa.ß",
    "karmelowe, karmelowy.ß, karmelowa.ß",
    "kawowe, kawowy.ß, kawowa.ß, coffee",
    "kokosowe, kokosowy.ß, kokosowa.ß",
    "miętowe, mietowe, miętowy, mietowy.ß, miętowa, mietowa.ß, mięta, mieta, peppermint.ß",
    "orzechowe, orzechowy.ß, orzechowa.ß, nut.ß",
    "owocowe, owocowy.ß, owocowa.ß",
    "śmietankowe, smietankowe, śmietankowy, smietankowy.ß, śmietankowa, smietankowa.ß",
    "waniliowe, wianiliowy.ß, waniliowa.ß"
];

let grains_pastaLabels = [
    "--group--Grupy",
    "Kasze",
    "Makarony",
    "Mąki",
    "Płatki",
    "Ryż",
    "Strączkowe",
    
    "--group--Kasze",
    "Bulgur",
    "Gryczana",
    "Jaglana",
    "Jęczmienna",
    "Kamut",
    "Kukurydziana",
    "Kuskus",
    "Manna",
    "Pęczak",
    
    "--group--Makarony",
    "Cannelloni",
    "Conchiglie",
    "Coquillettes",
    "Fusilli",
    "Gnocchi",
    "Lasagne",
    "Linguine",
    "Penne",
    "Ravioli",
    "Spaghetti",
    "Tagliatelle",
    "Tortellini",
    
    "--group--Mąki gluten.",
    "Pszen. jasna",
    "Pszen. razowa",
    "Semolina",
    "Jęczmienna",
    "Orkiszowa",
    "Żytnia",
    
    "--group--Mąki bezglut.",
    "Gryczana",
    "Jaglana",
    "Kokosowa",
    "Kukurydziana",
    "Migdałowa",
    "Owsiana",
    "Ryżowa",
    "Sojowa",
    
    "--group--Płatki",
    "Muesli",
    "Gryczane",
    "Jaglane",
    "Jęczmienne",
    "Kukurydziane",
    "Owsiane",
    "Ryżowe",
    
    "--group--Ryż",
    "Biały",
    "Basmati",
    "Jaśminowy",
    "Paraboliczny",
    "Sushi",
    "Brązowy",
    "Czarny",
    "Czerwony",
    "Żółty",
    
    "--group--Strączkowe",
    "Bób",
    "Ciecierzyca",
    "Fasola",
    "Groch",
    "Soczewica",
    "Soja",
    
    "--group--Inne",
    "Otręby",
    "Skrobia kukur.",
    "Skrobia ziem."
];
let grains_pastaList = [
    "--group--",
    "kasze, kasza.ß",
    "makarony",
    "mąki, maki.ß, mąka, maka",
    "płatki, platki",
    "ryż, ryz",
    "rośliny strączkowe, rosliny straczkowe, strączki, straczki.ß",
    
    "--group--",
    "bulglur",
    "gryczana, gryka.ß",
    "jaglana",
    "jęczmienna, jeczmienna, jęczmień, jeczmien.ß",
    "kamut",
    "kukurydziana, kukurydza.ß",
    "kuskus",
    "manna",
    "pęczak, peczak",
    
    "--group--",
    "cannelloni",
    "conchiglie, muszelki",
    "coquillettes, kolanka",
    "fusilli, świderki, swiderki",
    "gnocchi",
    "lasagne, lasagna",
    "linguine",
    "penne, rurki",
    "ravioli",
    "spaghetti",
    "tagliatelle, paski",
    "tortellini",
    
    "--group--",
    "mąka pszenna, maka pszenna, jasna, tortowa.ß, all-purpose.ß, all purpose.ß, typ 450.ß, typ 550.ß",
    "mąka pszenna, maka pszenna, ciemna, razowa, graham.ß",
    "semolina, mąka z pszenicy durum, maka z pszenicy durum",
    "mąka jęczmienna, maka jeczmienna",
    "mąka orkiszowa, maka orkiszowa",
    "mąka żytnia, maka zytnia",
    
    "--group--",
    "mąka gryczana, maka gryczana",
    "mąka jaglana, maka jaglana",
    "mąka kokosowa, maka kokosowa",
    "mąka kukurydziana, maka kukurydziana",
    "mąka migdałowa, maka migdalowa",
    "mąka owsiana, maka owsiana",
    "mąka ryżowa, maka ryzowa",
    "mąka sojowa, maka sojowa",
    
    "--group--",
    "muesli, musli.ß",
    "gryczane, gryka.ß",
    "jaglane",
    "jęczmienne, jeczmienne, jęczmień, jeczmien.ß",
    "kukurydziane, kukurydza.ß",
    "owsiane, owies",
    "ryżowe",
    
    "--group--",
    "biały, bialy, zwykły, zwykly.ß, normalny.ß",
    "basmati",
    "jaśminowy, jasminowy",
    "paraboliczny, paraboiled.ß",
    "sushi",
    "brązowy, brazowy",
    "czarny",
    "czerwony",
    "żółty, zolty",
    
    "--group--",
    "bób, bob",
    "ciecierzyca",
    "fasola",
    "groch, groszek.ß",
    "soczewica",
    "soja",
    
    "--group--",
    "otręby, otreby",
    "skrobia kukurydziana",
    "skrobia ziemniaczana"
];

let fruits_vegetablesLabels = [
    "--group--Grupy",
    "Owoce",
    "Warzywa",
    "Orzechy",
    "Grzyby",
    "Nasiona",
    
    "--group--Owoce",
    "Cytrusowe",
    "Egzotyczne",
    "Jagodowe",
    "Melonowe",
    "Ogrodowe",
    "Pestkowe",
    "Sadowe",
    "Tropikalne",
    "Kandyzowane",
    "Suszone",
    
    "--group--Warzywa",
    "Bulwowe",
    "Kapustne",
    "Korzeniowe",
    "Liściaste",
    
    "--group--Orzechy",
    "Brazylijskie",
    "Kasztany",
    "Kokosy",
    "Laskowe",
    "Macadamia",
    "Migdały",
    "Nerkowca",
    "Pekan",
    "Piniowe",
    "Pistacje",
    "Włoskie",
    "Ziemne",
    
    "--group--Grzyby",
    "Boczniaki",
    "Borowiki",
    "Kanie",
    "Koźlarze",
    "Kurki",
    "Maślaki",
    "Opieńki",
    "Pieczarki",
    "Podgrzybki",
    "Rydze",
    "Smardze",
    "Trufle",
    
    "--group--Nasiona",
    "Chia",
    "Dyni",
    "Mak",
    "Sezam",
    "Słonecznika",
    
    "--group--Opakowanie",
    "W puszce",
    "W słoiku",
    
    "--group--Właściwości",
    "Low-kcal",
    "High-kcal",
    "Low-carb",
    "High-carb",
    "High-protein",
    
    "--group--Smak",
    "Gorzkie",
    "Kwaśne",
    "Ostre",
    "Słodkie",
    "Słone",
    
    "--group--Kolory",
    "Białe",
    "Brązowe",
    "Czarne",
    "Czerwone",
    "Fioletowe",
    "Pomarańczowe",
    "Zielone",
    "Żółte"
];
let fruits_vegetablesList = [
    "--group--",
    "owoce",
    "warzywa, warzywo.ß",
    "orzechy, orzeszki.ß",
    "grzyby",
    "nasiona, nasiono.ß, pestki, pestka.ß",
    
    "--group--",
    "cytrusowe, cytrusy.ß",
    "egzotyczne, exotic.ß, egzotyki.ß",
    "jagodowe, leśne, lesne",
    "melonowe, melony.ß",
    "ogrodowe, działkowe, dzialkowe",
    "pestkowe, pestkowce.ß",
    "sadowe, sadownicze.ß",
    "tropkilane",
    "kandyzowane",
    "suszone, wysuszone.ß",
    
    "--group--",
    "bulwowe, bulwy, bulwa, bulwiaste.ß",
    "kapustne, kapuściane, kapusciane.ß",
    "korzeniowe, korzeniowate.ß, korzenie.ß, korzeń, korzen",
    "liściaste, lisciaste, liściowe, lisciowe.ß, liście, liscie.ß",
    
    "--group--",
    "brazylijskie",
    "kasztany, chestnuts",
    "kokosy, coconuts",
    "laskowe, hazelnuts",
    "macadamia, makadamia.ß, makadamiowe.ß",
    "migdały, migdaly, almonds",
    "nerkowca, nerkowiec.ß, nerkowce.ß, cashew",
    "pekan, pecan",
    "piniowe, pine",
    "pistacje, pistacja.ß, pistachios",
    "włoskie, wloskie, włoski, wloski.ß, walnut",
    "ziemne, ziemny, peanuts",
    
    "--group--",
    "boczniaki, oysters.ß",
    "borowiki, boletuses.ß",
    "kanie, kania.ß, kites.ß",
    "koźlarze, kozlarze, birch boletes.ß",
    "kurki, kurka.ß, pieprzniki.ß, chanterelles.ß",
    "maślaki, maslaki, boletuses.ß, slippery jack.ß",
    "opieńki, opienki, opieńka, opienka.ß, honey fungus.ß",
    "pieczarki, pieczarka.ß, champignons.ß",
    "podgrzybki, podgrzybek.ß, boletes.ß, porcino.ß",
    "rydze, saffron milk caps.ß",
    "smardze, morels.ß",
    "trufle, trufla.ß, truffles.ß",
    
    "--group--",
    "chia",
    "dyni, dyniowe.ß",
    "mak, maku.ß, maczek.ß",
    "sezam",
    "słonecznika, slonecznika, słonecznik, slonecznik.ß",
    
    "--group--",
    "w puszce, puszkowane, puszka.ß, z puszki.ß",
    "w słoiku, w sloiku, ze słoika, ze sloika.ß",
    
    "--group--",
    "low-kcal, low kcal.ß, niskokaloryczne, nisko kaloryczne.ß, diet.ß",
    "high-kcal, high kcal, wysokokaloryczne, wysoko kaloryczne.ß",
    "low-carb, low carb.ß, mało węglowodanów, malo weglowodanow, mało węgli, malo wegli.ß",
    "high-carb, high carb.ß, dużo węglowodanów, duzo weglowodanow, dużo węgli, duzo wegli.ß",
    "high-protein, high protein.ß, wysokobiałkowe, wysokobialkowe, wysoko białkowe, wysoko bialkowe.ß, dużo białka, duzo bialka.ß, białko, bialko",
    
    "--group--",
    "gorzkie, gorzki.ß, gorzka.ß",
    "kwaśne, kwasne, kwaśny, kwasny.ß, kwaśna, kwasna.ß",
    "ostre, ostry.ß, ostra.ß, piknatne, pikantny.ß, pikantna.ß",
    "słodkie, slodkie.ß, słodka, slodka.ß",
    "słone, slone, słony, slony.ß, słona, slona.ß",
    
    "--group--",
    "białe, biale, biały, bialy.ß, biała, biala.ß",
    "brązowe, brazowe, brązowy, brazowy.ß, brązowa, brazowa.ß",
    "czarne, czarny.ß, czarna.ß, ciemne.ß, ciemny.ß, ciemna.ß",
    "czerwone, czerwony.ß, czerwona.ß",
    "fioletowe, fioletowy.ß, fioletowa.ß, niebieskie.ß, niebieski.ß, niebieska.ß",
    "pomarańczowe, pomaranczowe, pomarańczowy, pomaranczowy.ß, pomarańczowa, pomaranczowa.ß",
    "zielone, zielony.ß, zielona.ß",
    "zółte, zolte, żółty, zolty.ß, żółta, zolta.ß, złote, zlote.ß, złoty, zloty.ß, złota, zlota.ß"
];

let meat_dairyLabels = [
    "--group--Grupy",
    "Mięso",
    "Nabiał",
    "Ser",
    "Jajka",
    
    "--group--Mięso",
    "Kurczak",
    "Wołowina",
    "Wieprzowina",
    "Dziczyzna",
    "Indyk",
    "Jagnięcina",
    "Baranina",
    "Cielęcina",
    "Owoce morza",
    "Ryby",
    
    "--subgroup--Rodzaj",
    "Boczek",
    "Burgery",
    "Kabanosy",
    "Kiełbasa",
    "Konserwy",
    "Mielone",
    "Parówki",
    "Pasztet",
    "Salami",
    "Szynka",
    
    "--group--Nabiał",
    "Jogurt",
    "Kefir",
    "Masło",
    "Mleko",
    "Skyr",
    "Śmietana",
    "Śmietanka",
    
    "--group--Sery",
    "Krowi",
    "Kozi",
    "Owczy",
    "Plastry",
    "Kostka",
    "Wiórki",
    "Topiony",
    
    "--subgroup--Miękkie",
    "Homogen.",
    "Mascarpone",
    "Mozarella",
    "Ricotta",
    "Serek wiejski",
    "Twaróg",
    
    "--subgroup--Twarde",
    "Cheddar",
    "Emmentaler",
    "Gouda",
    "Halloumi",
    "Mimolette",
    "Oscypek",
    "Permezan",
    
    "--subgroup--Pleśniowe",
    "Brie",
    "Camembert",
    "Feta",
    "Gorgonzola",
    "Roquefort",
    
    "--group--Jajka",
    "Kurze",
    "Gęsie",
    "Indycze",
    "Kacze",
    "Przepiórcze",
    "Strusie",
    
    "--group--Właściwości",
    "Low-kcal",
    "High-kcal",
    "Low-carb",
    "High-carb",
    "High-protein",
    "Low-fat",
    "High-fat",
    
    "--group--Smak",
    "Gorzkie",
    "Kwaśne",
    "Słodkie",
    "Słone",
    "Umami",
    "Czekoladowe",
    "Kakaowe",
    "Karmelowe",
    "Kawowe",
    "Kokosowe",
    "Miętowe",
    "Orzechowe",
    "Owocowe",
    "Śmietankowe",
    "Waniliowe"
];
let meat_dairyList = [
    "--group--",
    "mięso, mieso",
    "nabiał, nabial",
    "ser, sery.ß",
    "jajka, jajko.ß",
    
    "--group--",
    "kurczak, kura",
    "wołowina, wolowina, krowa.ß, krowy.ß",
    "wieprzowina, świnia, swinia.ß",
    "dziczyzna",
    "indyk",
    "jagnięcina, jagniecina, jagnię, jagnie.ß",
    "baranina, baran.ß",
    "cielęcina, cielecina, cielę, ciele.ß",
    "owoce morza",
    "ryby, ryba.ß",
    
    "--group--",
    "boczek, bekon",
    "burgery, patty",
    "kabanosy",
    "kiełbasa, kielbasa, kiełbasy, kielbasy.ß, kiełbaska, kielbaska.ß, kiełbaski, kielbaski.ß",
    "konserwy, konserwa.ß",
    "mielone, zmielone",
    "parówki, parowki, parówka, parowka.ß",
    "pasztet",
    "salami",
    "szynka",
    
    "--group--",
    "jogurt",
    "kefir",
    "masło, maslo",
    "mleko",
    "skyr",
    "śmietana, smietana",
    "śmietanka, smietanka",
    
    "--group--",
    "krowi, krowie.ß",
    "kozi, kozie.ß",
    "owczy, owcze.ß",
    "plastry, plasterki.ß, w plastrach.ß, w plasterkach.ß",
    "kostka, w kostce.ß",
    "wiórki, wiorki, we wiórkach, we wiorkach.ß",
    "topiony",
    
    "--group--",
    "homogenizowany, homogenizowane.ß",
    "mascarpone",
    "mozarella",
    "ricotta",
    "serek wiejski, cottage cheese",
    "twaróg, twarog, twarożek, twarozek.ß, quark.ß",
    
    "--group--",
    "cheddar",
    "emmentaler",
    "gouda",
    "halloumi, halumi.ß",
    "mimolette",
    "oscypek, oscypki.ß",
    "parmezan",
    
    "--group--",
    "brie",
    "camembert",
    "feta",
    "gorgonzola",
    "roquefort",
    
    "--group--",
    "kurze, od kury.ß",
    "gęsie, gesie, od gęsi, od gesi.ß",
    "indycze, od indyka.ß",
    "kacze, od kaczki.ß",
    "przepiórcze, przepiorcze, od przepiórki, od przepiorki.ß",
    "strusie, od strusia.ß",
    
    "--group--",
    "low-kcal, low kcal.ß, niskokaloryczne, nisko kaloryczne.ß, diet.ß",
    "high-kcal, high kcal, wysokokaloryczne, wysoko kaloryczne.ß",
    "low-carb, low carb.ß, mało węglowodanów, malo weglowodanow, mało węgli, malo wegli.ß",
    "high-carb, high carb.ß, dużo węglowodanów, duzo weglowodanow, dużo węgli, duzo wegli.ß",
    "high-protein, high protein.ß, wysokobiałkowe, wysokobialkowe, wysoko białkowe, wysoko bialkowe.ß, dużo białka, duzo bialka.ß, białko, bialko",
    "low-fat, low fat.ß, niskołuszczowe, niskotluszczowe, nisko tłuszczowe, nisko tluszczowe.ß, mało tłuszczu, malo tluszczu.ß, chude, chudy.ß, chuda.ß",
    "high-fat, high fat.ß, wysokotłuszczowe, wysokotluszczowe, wysoko tłuszczowe, wysoko tluszczowe.ß, dużo tłuszczu, duzo tluszczu.ß, tłuste, tluste, tłusty, tlusty.ß, tłusta, tlusta.ß",
    
    "--group--",
    "gorzkie, gorzki.ß, gorzka.ß",
    "kwaśne, kwasne, kwaśny, kwasny.ß, kwaśna, kwasna.ß",
    "słodkie, slodkie.ß, słodka, slodka.ß",
    "słone, slone, słony, slony.ß, słona, slona.ß",
    "umami",
    "czekoladowe, czekoladowy, czekoladowa",
    "kakaowe, kakaowy.ß, kakaowa.ß",
    "karmelowe, karmelowy.ß, karmelowa.ß",
    "kawowe, kawowy.ß, kawowa.ß, coffee",
    "kokosowe, kokosowy.ß, kokosowa.ß",
    "miętowe, mietowe, miętowy, mietowy.ß, miętowa, mietowa.ß, mięta, mieta, peppermint.ß",
    "orzechowe, orzechowy.ß, orzechowa.ß, nut.ß",
    "owocowe, owocowy.ß, owocowa.ß",
    "śmietankowe, smietankowe, śmietankowy, smietankowy.ß, śmietankowa, smietankowa.ß",
    "waniliowe, wianiliowy.ß, waniliowa.ß"
];

let vege_veganLabels = [
    "--group--Grupy",
    "Mięso",
    "Nabiał",
    "Ser",
    
    "--group--Składniki",
    "Ciecierzyca",
    "Fasola",
    "Grzyby",
    "Soczewica",
    "Soja",
    "Warzywa",
    "Zboże",
    
    "--group--Vege mięso",
    "Boczek",
    "Burgery",
    "Kabanosy",
    "Kiełbasa",
    "Klopsiki",
    "Kotlety",
    "Mielone",
    "Parówki",
    "Pasztet",
    "Salami",
    "Szynka",
    "Tofu",
    
    "--group--Vege nabiał",
    "Jogurt",
    "Kefir",
    "Masło",
    "Mleko",
    "Śmietana",
    "Śmietanka",
    
    "--group--Vege sery",
    "Plastry",
    "Kostka",
    "Wiórki",
    "Topiony",
    
    "--subgroup--Rodzaj",
    "Mozarella",
    "Serek wiejski",
    "Twaróg",
    "Cheddar",
    "Emmentaler",
    "Gouda",
    "Halloumi",
    "Mimolette",
    "Permezan",
    "Feta",
    "Gorgonzola",
    
    "--group--Właściwości",
    "Vege",
    "Vegan",
    "Low-kcal",
    "High-kcal",
    "Low-carb",
    "High-carb",
    "High-protein",
    "Low-fat",
    "High-fat",
    
    "--group--Smak",
    "Gorzkie",
    "Kwaśne",
    "Słodkie",
    "Słone",
    "Umami",
    "Czekoladowe",
    "Kakaowe",
    "Karmelowe",
    "Kawowe",
    "Kokosowe",
    "Miętowe",
    "Orzechowe",
    "Owocowe",
    "Śmietankowe",
    "Waniliowe"
];
let vege_veganList = [
    "--group--",
    "mięso, mieso",
    "nabiał, nabial",
    "ser, sery.ß",
    
    "--group--",
    "ciecierzyca, cieciorka.ß, z ciecierzycy",
    "fasola, fasolka.ß, z fasoli, z fasolki.ß, fasolowe, fasolowy.ß, fasolowa.ß",
    "grzyby, z grzybów, z grzybow, grzybowe, grzybowy.ß, grzybowa.ß",
    "soczewica, z soczewicy",
    "soja, z soi, sojowe, sojowy.ß, sojowa.ß",
    "warzywa, z warzyw, warzywne, warzywny.ß, warzywna.ß",
    "zboże, zboze, ze zboża, ze zboza, zbożowe, zbozowe, zbożowy, zbozowy.ß, zbożowa, zbozowa.ß",
    
    "--group--",
    "boczek, bekon",
    "burgery, patty",
    "kabanosy",
    "kiełbasa, kielbasa, kiełbasy, kielbasy.ß, kiełbaska, kielbaska.ß, kiełbaski, kielbaski.ß",
    "klopsiki, klopsy",
    "kotlety, kotleciki.ß",
    "mielone, zmielone",
    "parówki, parowki, parówka, parowka.ß",
    "pasztet",
    "salami",
    "szynka",
    "tofu",
    
    "--group--",
    "jogurt",
    "kefir",
    "masło, maslo",
    "mleko",
    "śmietana, smietana",
    "śmietanka, smietanka",
    
    "--group--",
    "plastry, plasterki.ß, w plastrach.ß, w plasterkach.ß",
    "kostka, w kostce.ß",
    "wiórki, wiorki, we wiórkach, we wiorkach.ß",
    "topiony",
    
    "--group--",
    "mozarella",
    "serek wiejski, cottage cheese",
    "twaróg, twarog, twarożek, twarozek.ß, quark.ß",
    "cheddar",
    "emmentaler",
    "gouda",
    "halloumi, halumi.ß",
    "mimolette",
    "parmezan",
    "feta",
    "gorgonzola",
    
    "--group--",
    "vege, wege.ß, vegetarian.ß, wegetariańskie, wegetarianskie, wegetariańska, wegetarianska.ß, bez mięsa, bez miesa, bezmięsne, bezmiesne, bezmięsny, bezmiesny.ß, bezmięsna, bezmiesna.ß",
    "vegan, wegan, wegańskie, weganskie, wegańska, weganska.ß, bez mięsa, bez miesa, bezmięsne, bezmiesne, bezmięsny, bezmiesny.ß, bezmięsna, bezmiesna.ß, bez mleka.ß, bez jaj.ß, bez jajek.ß, bez nabiału, bez nabialu.ß",
    "low-kcal, low kcal.ß, niskokaloryczne, nisko kaloryczne.ß, diet.ß",
    "high-kcal, high kcal, wysokokaloryczne, wysoko kaloryczne.ß",
    "low-carb, low carb.ß, mało węglowodanów, malo weglowodanow, mało węgli, malo wegli.ß",
    "high-carb, high carb.ß, dużo węglowodanów, duzo weglowodanow, dużo węgli, duzo wegli.ß",
    "high-protein, high protein.ß, wysokobiałkowe, wysokobialkowe, wysoko białkowe, wysoko bialkowe.ß, dużo białka, duzo bialka.ß, białko, bialko",
    "low-fat, low fat.ß, niskołuszczowe, niskotluszczowe, nisko tłuszczowe, nisko tluszczowe.ß, mało tłuszczu, malo tluszczu.ß, chude, chudy.ß, chuda.ß",
    "high-fat, high fat.ß, wysokotłuszczowe, wysokotluszczowe, wysoko tłuszczowe, wysoko tluszczowe.ß, dużo tłuszczu, duzo tluszczu.ß, tłuste, tluste, tłusty, tlusty.ß, tłusta, tlusta.ß",
    
    "--group--",
    "gorzkie, gorzki.ß, gorzka.ß",
    "kwaśne, kwasne, kwaśny, kwasny.ß, kwaśna, kwasna.ß",
    "słodkie, slodkie.ß, słodka, slodka.ß",
    "słone, slone, słony, slony.ß, słona, slona.ß",
    "umami",
    "czekoladowe, czekoladowy, czekoladowa",
    "kakaowe, kakaowy.ß, kakaowa.ß",
    "karmelowe, karmelowy.ß, karmelowa.ß",
    "kawowe, kawowy.ß, kawowa.ß, coffee",
    "kokosowe, kokosowy.ß, kokosowa.ß",
    "miętowe, mietowe, miętowy, mietowy.ß, miętowa, mietowa.ß, mięta, mieta, peppermint.ß",
    "orzechowe, orzechowy.ß, orzechowa.ß, nut.ß",
    "owocowe, owocowy.ß, owocowa.ß",
    "śmietankowe, smietankowe, śmietankowy, smietankowy.ß, śmietankowa, smietankowa.ß",
    "waniliowe, wianiliowy.ß, waniliowa.ß"
];

let ready_mealsLabels = [
    "--group--Grupy",
    "Fast foody",
    "Obiady",
    
    "--group--Fast foody",
    "Burgery",
    "Burrito",
    "Corn dog",
    "Frytki",
    "Kebab",
    "Lasagne",
    "Mac & cheese",
    "Nuggety",
    "Pizza",
    "Skrzydełka",
    "Wrap",
    "Zapiekanki",
    
    "--group--Obiady",
    "3 częściowy",
    "Fasolka",
    "Gołąbki",
    "Klopsiki",
    "Knedle",
    "Kopytka",
    "Krokiety",
    "Makarony",
    "Pierogi",
    "Pyzy",
    "Zupy",
    
    "--group--Inne",
    "Hummus",
    "Kanapki",
    "Sałatka",
    "Surówka",
    "Sajgonki",
    "Paluszki rybne",
    "Sushi",
    
    "--group--Przygotowanie",
    "Bez przygot.",
    "Do odgrzania",
    "Do ugotow.",
    "Do upiecz.",
    "Mrożone",
    "W słoiku",
    
    "--group--Właściwości",
    "Z mięsem",
    "Vege",
    "Vegan",
    "Low-kcal",
    "High-kcal",
    "Low-carb",
    "High-carb",
    "High-protein",
    "Low-fat",
    "High-fat",
    
    "--group--Smak",
    "Kwaśne",
    "Ostre",
    "Słodkie",
    "Słone",
    "Umami"
];
let ready_mealsList = [
    "--group--",
    "fast food, fast foody.ß, śmieciowe jedzenie, smieciowe jedzenie",
    "obiad, obiady.ß, dania obiadowe, danie obiadowe.ß, lunch.ß, dinner.ß",
    
    "--group--",
    "burgery, hamburgery.ß, cheeseburgery.ß",
    "burrito",
    "corn dog, corndog.ß",
    "frytki",
    "kebab, kebap.ß, gyros.ß",
    "lasagne, lasagna.ß",
    "mac & cheese, mac and cheese.ß, macaroni & cheese.ß, macaroni & cheese, makaron z serem, makaron i ser.ß",
    "nuggety",
    "pizza",
    "skrzydełka, skrzydelka, chicken wings",
    "wrap, tortilla",
    "zapiekanki, zapiekanka.ß",

    "--group--",
    "3 częściowy, 3 czesciowy, trój częściowy, troj czesciowy.ß,  standardowy obiad.ß, zwykły obiad, zywkly obiad.ß",
    "fasolka, fasola.ß",
    "gołąbki, golabki",
    "klopsiki, klopsy.ß",
    "knedle, knedliki.ß",
    "kopytka",
    "krokiety",
    "makarony",
    "pierogi, pierożki, pierozki.ß",
    "pyzy",
    "zupy, zupa.ß",
    
    "--group--",
    "hummus, pasta z ciecierzycy",
    "kanapki, kanapka.ß, sandwich.ß",
    "sałatka, salatka",
    "surówka, surowka",
    "sajgonki, sajgonka.ß, spring rolls",
    "paluszki rybne",
    "sushi",
    
    "--group--",
    "bez przygotowania, bez przygotowywania.ß, gotowe od razu.ß, bez obróbki cieplnej, bez obrobki cieplnej",
    "do odgrzania, do odgrzewania.ß, odgrzanie.ß, odgrzewanie.ß, odgrzane.ß, odgrzany.ß, odgrzana.ß, do mikrofali.ß",
    "do ugotowania, do gotowania.ß, ugotowanie.ß, gotowanie.ß, ugotowane.ß, ugotowany.ß, ugotowana.ß",
    "do upieczenia, do pieczenia.ß, do piekarnika, piekarnik.ß, pieczone, pieczony.ß, pieczona.ß",
    "mrożone, mrozone, mrożonki, mrozonki, mrożonka, mrozonka.ß, zamrożone, zamrozone.ß",
    "w słoiku, w sloiku, słoik, sloik.ß",
    
    "--group--",
    "z mięsem, z miesem, mięsne, miesne.ß, mięso, mieso",
    "vege, wege.ß, vegetarian.ß, wegetariańskie, wegetarianskie, wegetariańska, wegetarianska.ß, bez mięsa, bez miesa, bezmięsne, bezmiesne, bezmięsny, bezmiesny.ß, bezmięsna, bezmiesna.ß",
    "vegan, wegan, wegańskie, weganskie, wegańska, weganska.ß, bez mięsa, bez miesa, bezmięsne, bezmiesne, bezmięsny, bezmiesny.ß, bezmięsna, bezmiesna.ß, bez mleka.ß, bez jaj.ß, bez jajek.ß, bez nabiału, bez nabialu.ß",
    "low-kcal, low kcal.ß, niskokaloryczne, nisko kaloryczne.ß, diet.ß",
    "high-kcal, high kcal, wysokokaloryczne, wysoko kaloryczne.ß",
    "low-carb, low carb.ß, mało węglowodanów, malo weglowodanow, mało węgli, malo wegli.ß",
    "high-carb, high carb.ß, dużo węglowodanów, duzo weglowodanow, dużo węgli, duzo wegli.ß",
    "high-protein, high protein.ß, wysokobiałkowe, wysokobialkowe, wysoko białkowe, wysoko bialkowe.ß, dużo białka, duzo bialka.ß, białko, bialko",
    "low-fat, low fat.ß, niskołuszczowe, niskotluszczowe, nisko tłuszczowe, nisko tluszczowe.ß, mało tłuszczu, malo tluszczu.ß, chude, chudy.ß, chuda.ß",
    "high-fat, high fat.ß, wysokotłuszczowe, wysokotluszczowe, wysoko tłuszczowe, wysoko tluszczowe.ß, dużo tłuszczu, duzo tluszczu.ß, tłuste, tluste, tłusty, tlusty.ß, tłusta, tlusta.ß",
    
    "--group--",
    "kwaśne, kwasne, kwaśny, kwasny.ß, kwaśna, kwasna.ß",
    "ostre, ostry.ß, ostra.ß, piknatne, pikantny.ß, pikantna.ß",
    "słodkie, slodkie.ß, słodka, slodka.ß",
    "słone, slone, słony, slony.ß, słona, slona.ß",
    "umami"
];

let semi_finishedLabels = [
    "--group--Grupy",
    "Napoje",
    "Przekąski",
    "Desery",
    "Ciasta",
    
    "--group--Napoje",
    "Czekolada",
    "Energetyki",
    "Herbata",
    "Kakao",
    "Kawa",
    "Lemoniada",
    "Oranżada",
    "Smoothie",

    "--group--Przekąski",
    "Noodles",
    "Puree",
    "Zupki instant",
    "Zupy",

    "--group--Desery",
    "Budyń",
    "Galaretka",
    "Kaszka",
    "Kisiel",
    "Mleczny ryż",
    "Owsianka",

    "--group--Ciasta",
    "Babka",
    "Ciastka",
    "Kremówka",
    "Muffinki",
    "Pierniczki",
    "Piernik",
    "Sernik",
    "Tort",

    "--group--Inne",
    "Bita Śmietana",
    "Kremy",
    
    "--group--Właściwości",
    "Low-kcal",
    "High-kcal",
    "Low-carb",
    "High-carb",

    "--group--Smak",
    "Gorzkie",
    "Kwaśne",
    "Ostre",
    "Słodkie",
    "Słone",
    "Umami",
    "Czekoladowe",
    "Kakaowe",
    "Karmelowe",
    "Kawowe",
    "Kokosowe",
    "Miętowe",
    "Orzechowe",
    "Owocowe",
    "Śmietankowe",
    "Waniliowe"
];
let semi_finishedList = [
    "--group--",
    "napoje, napój, napoj, picie.ß, napój instant, napoj instant, napoje instant.ß, drinki.ß,",
    "przekąski, przekaski, przekąski instant, przekaski instant, snacks.ß",
    "desery, deserki.ß, desery instant",
    "ciasta, ciasta w proszku, wypieki",

    "--group--",
    "czekolada, gorąca czekolada, goraca czekolada.ß, czekolada do picia",
    "energetyki, napój energetyczny, napoj energetyczny, energy drink, energetyk instant",
    "herbata",
    "kakao",
    "kawa",
    "lemoniada",
    "oranżada, oranzada",
    "smoothie",

    "--group--",
    "noodles, nudle.ß, makaron instant",
    "puree, ziemniaczane.ß",
    "zupki instant, zupka instant.ß, zupka w proszku, zupki w proszku.ß, zupka chińska, zupka chinska, zupki chińskie, zupki chinskie.ß",
    "zupy, zupa.ß, zupa z torebki.ß, zupa z paczki",

    "--group--",
    "budyń, budyn, pudding",
    "galaretka",
    "kaszka, kasza.ß, kaszka w kubku, kasza z kubka.ß",
    "kisiel",
    "mleczny ryż, mleczny ryz, ryż na mleku, ryz na mleku.ß, ryż z mlekiem, ryz z mlekiem.ß, ryż w kubku, ryz w kubku",
    "owsianka",

    "--group--",
    "babka, babka piaskowa.ß",
    "ciastka",
    "kremówka, kremowka, kremówki, kremowki.ß",
    "muffinki, muffinka.ß, babeczki, babeczka.ß",
    "pierniczki, gingerbreads.ß, ginderbread cookies.ß",
    "piernik",
    "sernik, cheesecake.ß",
    "tort, urodzinowy.ß",

    "--group--",
    "bita śmietana, bita smietana",
    "kremy, krem do tortu.ß, krem tortowy.ß",

    "--group--",
    "low-kcal, low kcal.ß, niskokaloryczne, nisko kaloryczne.ß, diet.ß",
    "high-kcal, high kcal, wysokokaloryczne, wysoko kaloryczne.ß",
    "low-carb, low carb.ß, mało węglowodanów, malo weglowodanow, mało węgli, malo wegli.ß",
    "high-carb, high carb.ß, dużo węglowodanów, duzo weglowodanow, dużo węgli, duzo wegli.ß",
    
    "--group--",
    "gorzkie, gorzki.ß, gorzka.ß",
    "kwaśne, kwasne, kwaśny, kwasny.ß, kwaśna, kwasna.ß",
    "ostre, ostry.ß, ostra.ß, piknatne, pikantny.ß, pikantna.ß",
    "słodkie, slodkie.ß, słodka, slodka.ß",
    "słone, slone, słony, slony.ß, słona, slona.ß",
    "umami",
    "czekoladowe, czekoladowy, czekoladowa",
    "kakaowe, kakaowy.ß, kakaowa.ß",
    "karmelowe, karmelowy.ß, karmelowa.ß",
    "kawowe, kawowy.ß, kawowa.ß, coffee",
    "kokosowe, kokosowy.ß, kokosowa.ß",
    "miętowe, mietowe, miętowy, mietowy.ß, miętowa, mietowa.ß, mięta, mieta, peppermint.ß",
    "orzechowe, orzechowy.ß, orzechowa.ß, nut.ß",
    "owocowe, owocowy.ß, owocowa.ß",
    "śmietankowe, smietankowe, śmietankowy, smietankowy.ß, śmietankowa, smietankowa.ß",
    "waniliowe, wianiliowy.ß, waniliowa.ß"
];

let sauces_spicesLabels = [
    "--group--Grupy",
    "Sosy obiad.",
    "Sosy dodatki",
    "Dipy",
    "Przyprawy",

    "--group--Sosy",
    "W proszku",
    "W słoiku",

    "--group--Obiadowe",
    "Bolognese",
    "Meksykański",
    "Paprykowy",
    "Pomidorowy",
    "Słod.-kwaś.",
    "Tikka Masala",
    "Carbonara",
    "Curry",
    "Grzybowy",
    "Piecz. ciemny",
    "Piecz. jasny",
    "Serowy",
    "Śmietanowy",

    "--group--Dodatki",
    "BBQ",
    "Chili",
    "Czosnkowy",
    "Ketchup",
    "Majonez",
    "Musztarda",
    "Ogórkowy",
    "Ranch",
    "Tabasco",
    "Tysiąca Wysp",

    "--group--Dipy",
    "Ajvar",
    "Guacamole",
    "Hummus",
    "Salsa",
    "Serowy",
    "Tzatziki",

    "--group--Inne",
    "Chrzan",
    "Dressing",
    "Koncen. pom.",
    "Pesto",
    "Sos sojowy",
    "Sos owocowy",
    "Wasabi",

    "--group--Przyprawy",
    "Sól",
    "Pieprz",
    "MSG",
    "Bazylia",
    "Chili",
    "Cynamon",
    "Czosnek",
    "Gałka musz.",
    "Imbir",
    "Kminek",
    "Kurkuma",
    "Mięta",
    "Oregano",
    "Papryka",
    "Tymianek",

    "--subgroup--Mieszanki przyp.",
    "Chińska",
    "Curry",
    "Do gyrosa",
    "Do kurczaka",
    "Garam Masala",
    "Korzenna",
    "Piernikowa",
    "Zioła",
    
    "--group--Właściwości",
    "Vege",
    "Vegan",
    "Low-kcal",
    "High-kcal",
    "Low-carb",
    "High-carb",
    "High-protein",
    "Low-fat",
    "High-fat",

    "--group--Smak",
    "Gorzkie",
    "Kwaśne",
    "Ostre",
    "Słodkie",
    "Słone",
    "Umami"
];
let sauces_spicesList = [
    "--group--",
    "sosy obiadowe, sosy do obiadu.ß",
    "sosy dodatki",
    "dipy",
    "przyprawy, przyprawa.ß",
    
    "--group--",
    "w proszku, proszek.ß, sproszkowane.ß, sproszkowany.ß, sproszkowana.ß, sos instant, sos z paczki, sos z torebki.ß",
    "w słoiku, w sloiku, słoik, sloik.ß, sos ze słoika, sos ze sloika",
    
    "--group--",
    "bolognese",
    "meksykański, meksykanski",
    "paprykowy",
    "pomidorowy",
    "słodko-kwaśny, slodko-kwasny, słodko kwaśny, slodko kwasny.ß",
    "tikka masala, tika masala.ß",
    "carbonara",
    "curry",
    "grzybowy",
    "pieczeniowy ciemny, brown gravy",
    "pieczeniowy jasny",
    "serowy",
    "śmietanowy, smietanowy",
    
    "--group--",
    "BBQ, barbecue.ß, sos do grilla",
    "chili",
    "czosnkowy, czostkowy.ß",
    "ketchup, keczup.ß",
    "majonez, mayo",
    "musztarda",
    "ogórkowy, ogorkowy",
    "ranch",
    "tabasco",
    "tysiąca wysp, tysiaca wysp, 1000 wysp.ß",
    
    "--group--",
    "ajvar",
    "gracamole, avocado dip, dip awokado.ß",
    "hummus",
    "salsa",
    "serowy, queso, cheese dip",
    "tzatziki",
    
    "--group--",
    "chrzan",
    "dressing",
    "koncentrat pomidorowy",
    "pesto",
    "sos sojowy, soy sauce.ß",
    "sos owocowy",
    "wasabi, chrzan wasabi.ß",
    
    "--group--",
    "sól, sol",
    "pieprz",
    "MSG, glutaminian sodu, glutaminian monosodowy.ß",
    "bazylia",
    "chili",
    "cynamon",
    "czosnek",
    "gałka muszkatołowa, galka muszkatolowa",
    "imbir",
    "kminek",
    "kurkuma",
    "mięta, mieta",
    "oregano",
    "papryka",
    "tymianek",
    
    "--group--",
    "chińska, chinska, przyprawa chińska, przyprawa chinska.ß",
    "curry, przyprawa curry.ß",
    "przyprawa do gyrosa",
    "przyprawa do kurczaka",
    "garam masala",
    "przyprawa korzenna",
    "przyprawa do piernika, piernikowa.ß",
    "zioła, ziola, mieszanka ziół, mieszanka ziol",
    
    "--group--",
    "vege, wege.ß, vegetarian.ß, wegetariańskie, wegetarianskie, wegetariańska, wegetarianska.ß, bez mięsa, bez miesa, bezmięsne, bezmiesne, bezmięsny, bezmiesny.ß, bezmięsna, bezmiesna.ß",
    "vegan, wegan, wegańskie, weganskie, wegańska, weganska.ß, bez mięsa, bez miesa, bezmięsne, bezmiesne, bezmięsny, bezmiesny.ß, bezmięsna, bezmiesna.ß, bez mleka.ß, bez jaj.ß, bez jajek.ß, bez nabiału, bez nabialu.ß",
    "low-kcal, low kcal.ß, niskokaloryczne, nisko kaloryczne.ß, diet.ß",
    "high-kcal, high kcal, wysokokaloryczne, wysoko kaloryczne.ß",
    "low-carb, low carb.ß, mało węglowodanów, malo weglowodanow, mało węgli, malo wegli.ß",
    "high-carb, high carb.ß, dużo węglowodanów, duzo weglowodanow, dużo węgli, duzo wegli.ß",
    "high-protein, high protein.ß, wysokobiałkowe, wysokobialkowe, wysoko białkowe, wysoko bialkowe.ß, dużo białka, duzo bialka.ß, białko, bialko",
    "low-fat, low fat.ß, niskołuszczowe, niskotluszczowe, nisko tłuszczowe, nisko tluszczowe.ß, mało tłuszczu, malo tluszczu.ß, chude, chudy.ß, chuda.ß",
    "high-fat, high fat.ß, wysokotłuszczowe, wysokotluszczowe, wysoko tłuszczowe, wysoko tluszczowe.ß, dużo tłuszczu, duzo tluszczu.ß, tłuste, tluste, tłusty, tlusty.ß, tłusta, tlusta.ß",
    
    "--group--",
    "gorzkie, gorzki.ß, gorzka.ß",
    "kwaśne, kwasne, kwaśny, kwasny.ß, kwaśna, kwasna.ß",
    "ostre, ostry.ß, ostra.ß, piknatne, pikantny.ß, pikantna.ß",
    "słodkie, slodkie.ß, słodka, slodka.ß",
    "słone, slone, słony, slony.ß, słona, slona.ß",
    "umami"
];

let otherLabels = [
    "--group--Rodzaje",
    "Oleje",
    "Słodziki",
    "Do wypieków",

    "--group--Oleje",
    "Kokosowy",
    "Konopny",
    "Lniany",
    "Oliwa",
    "Orzechowy",
    "Rzepakowy",
    "Sezamowy",
    "Sojowy",
    "Słonecznik.",
    "Z awokado",

    "--group--Słodziki",
    "Cukier",
    "Erytrol",
    "Ksylitol",
    "Miód",
    "Stewia",
    "Syrop daktyl.",
    "Syrop klonowy",

    "--group--Do wypieków",
    "Agar",
    "Drożdże",
    "Prosz. do pie.",
    "Soda",
    "Żelatyna",
    "Aromaty",
    "Barwniki",
    "Posyp. cukier.",
    "Mleko sprosz.",

    "--group--Inne",
    "Bulion",
    "Masło orzech.",
    "Nori",
    "Ocet",
    "Papier ryżowy"
];
let otherList = [
    "--group--",
    "oleje",
    "słodziki, slodziki, dosładzacze, dosladzacze.ß",
    "do wypieków, do wypiekow, do ciast.ß, do pieczenia",
    
    "--group--",
    "kokosowy",
    "konopny",
    "lniany",
    "oliwa, oliwkowy",
    "orzechowy",
    "rzepakowy",
    "sezamowy",
    "sojowy",
    "słonecznikowy, slonecznikowy",
    "z awokado",
    
    "--group--",
    "cukier, sacharoza",
    "erytrol, erytrytol.ß",
    "ksylitol",
    "miód, miod",
    "stewia, stevia.ß",
    "syrop daktylowy",
    "syrop klonowy",
    
    "--group--",
    "agar, proszek agar.ß",
    "drożdże, drozdze",
    "proszek do pieczenia, baking powder.ß",
    "soda oczyszczona, soda do pieczenia.ß",
    "żelatyna, zelatyna",
    "aromaty, zapachy.ß",
    "barwniki, zabarwiacze.ß",
    "posypka do ciast, posypka kolorowa, cukiereczki.ß, hundreds and thousands",
    "mleko w proszku, sproszkowane mleko.ß",
    
    "--group--",
    "bulion, stock.ß, broth.ß",
    "masło orzechowe, maslo orzechowe, peanut butter",
    "wodorosty nori, sushi nori",
    "ocet",
    "papier ryżowy, papier ryzowy, papier do sajgonek"
];

