
let tagLabels = [
    "--group--Typ",
    "Śniadanie",
    "Obiad",
    "Kolacja",
    "Przekąska",
    "Słodycze",
    "Fast food",
    
    "--group--Składniki",
    "Mięso",
    "Nabiał",
    "Ser",
    "Owoce",
    "Warzywa",
    "Mąka",
    "Orzechy",
    "Grzyby",
    "Jajka",
    "Nasiona",
    "Alkohol",

    "--group--Mięso",
    "Kurczak",
    "Wołowina",
    "Wieprzowina",
    "Dziczyzna",
    "Indyk",
    "Jagnięcina",
    "Baranina",
    "Cielęcina",
    "Owoce morza",
    "Ryby",
    
    "--group--Nabiał",
    "Jogurt",
    "Kefir",
    "Masło",
    "Mleko",
    "Skyr",
    "Śmietana",
    "Śmietanka",
    
    "--group--Ser",
    "Mozarella",
    "Twaróg",
    "Cheddar",
    "Emmentaler",
    "Gouda",
    "Halloumi",
    "Mimolette",
    "Permezan",
    "Feta",
    "Gorgonzola",
    
    "--group--Owoce",
    "Cytrusowe",
    "Egzotyczne",
    "Jagodowe",
    "Melonowe",
    "Ogrodowe",
    "Pestkowe",
    "Sadowe",
    "Tropikalne",
    "Kandyzowane",
    "Suszone",
    
    "--group--Warzywa",
    "Cebula",
    "Czosnek",
    "Marchewki",
    "Pietruszka",
    "Rzodkiewki",
    "Ziemniaki",
    "Brokuł",
    "Kalafior",
    "Kapusta",
    "Sałata",
    "Szpinak",
    "Bób",
    "Ciecierzyca",
    "Fasola",
    "Groch",
    "Kukurydza",
    "Soczewica",
    "Soja",
    
    "--group--Mąka",
    "Pszenna",
    "Jęczmienna",
    "Orkiszowa",
    "Żytnia",
    "Gryczana",
    "Jaglana",
    "Kukurydziana",
    "Owsiana",
    "Ryżowa",
    "Ziemniaczana",
    "Kokosowa",
    "Migdałowa",
    "Pełnoziarnista",

    "--group--Region",
    "USA/Kanada",
    "Meks./Hiszp.",
    "Francja",
    "Włochy",
    "Eur. Środ./Płn.",
    "Eur. Wsch.",
    "Bliski Wsch.",
    "Indie",
    "Chiny",
    "Azja Płd.",
    "Japonia",
    
    "--group--Smak",
    "Gorzkie",
    "Kwaśne",
    "Słodkie",
    "Słone",
    "Umami",
    
    "--group--Przyrządzenie",
    "Ciepłe",
    "Zimne",
    "Pieczone",
    "Smażone",
    "Gotowane",
    "Na parze",
    
    "--group--Właściwości",
    "Low-kcal",
    "High-kcal",
    "Low-carb",
    "High-carb",
    "High-protein",
    "Low-fat",
    "High-fat",
    "Low-GI",
    "Medium-GI",
    "High-GI",
    "Lekkie",
    "Ciężkie",
    "Syte",
    "Vege",
    "Vegan",
    "Szybkie",
    "Tanie",
    "Drogie"
];
    
let tagList = [
    "--group--",
    "śniadanie, sniadanie",
    "obiad",
    "kolacja",
    "przekąski, przekaski, przekąska, przekaska.ß",
    "słodycze, slodycze, słodkości, slodkosci.ß",
    "fast food, śmieciowe jedzenie, smieciowe jedzenie.ß",
    
    "--group--",
    "mięso, mieso",
    "nabiał, nabial",
    "ser, sery.ß",
    "owoce",
    "warzywa, warzywo.ß",
    "mąka, maka",
    "orzechy, orzeszki.ß",
    "grzyby",
    "jajka, jajko.ß",
    "nasiona, nasiono.ß, pestki, pestka.ß",
    "alkohol, alkoholowe.ß, alkoholowy.ß, alkoholowa.ß",
    
    "--group--",
    "kurczak, kura",
    "wołowina, wolowina, krowa.ß, krowy.ß",
    "wieprzowina, świnia, swinia.ß",
    "dziczyzna",
    "indyk",
    "jagnięcina, jagniecina, jagnię, jagnie.ß",
    "baranina, baran.ß",
    "cielęcina, cielecina, cielę, ciele.ß",
    "owoce morza",
    "ryby, ryba.ß",
    
    "--group--",
    "jogurt",
    "kefir",
    "masło, maslo",
    "mleko",
    "skyr",
    "śmietana, smietana",
    "śmietanka, smietanka",
    
    "--group--",
    "mozarella",
    "twaróg, twarog, twarożek, twarozek.ß, quark.ß",
    "cheddar",
    "emmentaler",
    "gouda",
    "halloumi, halumi.ß",
    "mimolette",
    "parmezan",
    "feta",
    "gorgonzola",
    
    "--group--",
    "cytrusowe, cytrusy.ß",
    "egzotyczne, exotic.ß, egzotyki.ß",
    "jagodowe, leśne, lesne",
    "melonowe, melony.ß",
    "ogrodowe, działkowe, dzialkowe",
    "pestkowe, pestkowce.ß",
    "sadowe, sadownicze.ß",
    "tropkilane",
    "kandyzowane",
    "suszone",
    
    "--group--",
    "cebula, cebulka.ß",
    "czosnek",
    "marchewki, marchewka.ß",
    "pietruszka",
    "rzodkiewki",
    "ziemniaki, pyry.ß, kartofle.ß",
    "brokuł, brokul",
    "kalafior",
    "kapusta",
    "sałata, salata",
    "szpinak",
    "bób, bob",
    "ciecierzyca, cieciorka.ß",
    "fasola, fasolka.ß",
    "groch, groszek.ß",
    "kukurydza",
    "soczewica",
    "soja, sojowe.ß, sojowy.ß, sojowa.ß",
    
    "--group--",
    "pszenna",
    "jęczmienna, jeczmienna",
    "orkiszowa",
    "żytnia, zytnia",
    "gryczana",
    "jaglana",
    "kukurydziana",
    "owsiana",
    "ryżowa",
    "ziemniaczana",
    "kokosowa",
    "migdałowa, migdalowa",
    "pełnoziarnista, pelnoziarnista",
    
    "--group--",
    "kuchnia amerykańska, kuchnia amerykanska, ameryka, usa.ß, kanada.ß, kuchnia kanadyjska.ß",
    "kuchnia meksykańska, kuchnia meksykanska, kuchnia hiszpańska, kuchnia hiszpanska, meksyk, hiszpania",
    "kuchnia fransucka, francja",
    "kuchnia włoska, kuchnia wloska, włochy, wlochy",
    "kuchnia europejska, europa środkowa, europa srodkowa, północna, europa polnocna, płn., europa pln.ß",
    "kuchnia europejska, europa wschodnia",
    "kuchnia blisko wschodnia, kuchnia arabska, bliski wschód, bliski wschod.ß",
    "kuchnia indyjska, kuchnia hinduska, indie, hindi.ß",
    "kuchnia chińska, kuchnia chinska, chiny, chińszczyzna, chinszczyzna.ß",
    "kuchnia azjatycka, azja południowa, azja poludniowa, płd., azja pld.ß",
    "kuchnia japońska, kuchnia japonska, japonia",
    
    "--group--",
    "gorzkie, gorzki.ß, gorzka.ß",
    "kwaśne, kwasne, kwaśny, kwasny.ß, kwaśna, kwasna.ß",
    "słodkie, slodkie.ß, słodka, slodka.ß",
    "słone, slone, słony, slony.ß, słona, slona.ß",
    "umami",

    "--group--",
    "ciepłe, cieple, ciepły, cieply.ß, ciepła, ciepla.ß, na ciepło, na cieplo, gorące, gorace, gorący, goracy.ß, gorąca, goraca.ß",
    "zimne, zimny.ß, zimna.ß, na zimno, ice, iced, mrożone, mrozone.ß, morożony, mrozony.ß, mrożona, mrozona.ß",
    "pieczone, pieczony.ß, pieczona.ß, upieczone, upieczony.ß, upieczona.ß",
    "smażone, smazone, smażony, smazony.ß, smażona, smazona.ß, usmażone, usmazone, usmażony, usmazony.ß, usmażona, usmazona.ß",
    "gotowane, gotowany.ß, gotowana.ß, ugotowane, ugotowany.ß, ugotowana.ß",
    "gotowane na parze, ugotowane na parze.ß, ugotowany.ß, ugotowana.ß",
    
    "--group--",
    "low-kcal, low kcal.ß, niskokaloryczne, nisko kaloryczne.ß, diet.ß",
    "high-kcal, high kcal, wysokokaloryczne, wysoko kaloryczne.ß",
    "low-carb, low carb.ß, mało węglowodanów, malo weglowodanow, mało węgli, malo wegli.ß",
    "high-carb, high carb.ß, dużo węglowodanów, duzo weglowodanow, dużo węgli, duzo wegli.ß",
    "high-protein, high protein.ß, wysokobiałkowe, wysokobialkowe, wysoko białkowe, wysoko bialkowe.ß, dużo białka, duzo bialka.ß, białko, bialko",
    "low-fat, low fat.ß, niskołuszczowe, niskotluszczowe, nisko tłuszczowe, nisko tluszczowe.ß, mało tłuszczu, malo tluszczu.ß, chude, chudy.ß, chuda.ß",
    "high-fat, high fat.ß, wysokotłuszczowe, wysokotluszczowe, wysoko tłuszczowe, wysoko tluszczowe.ß, dużo tłuszczu, duzo tluszczu.ß, tłuste, tluste, tłusty, tlusty.ß, tłusta, tlusta.ß",
    "low-gi, low gi.ß, low glycemic index.ß, niski indeks glikemiczny.ß, niski IG",
    "medium-gi, medium gi.ß, med-gi.ß, med gi.ß, mid-gi.ß, mid gi.ß, medium glycemic index, średni indeks glikemiczny, sredni indeks glikemiczny.ß, sredni IG",
    "high-gi, high gi.ß, high glycemic index.ß, wysoki indeks glikemiczny.ß, wysoki IG",
    "lekkie, lekki.ß, lekka.ß",
    "ciężkie, ciezkie, ciężki, ciezki.ß, ciężka, ciezka.ß",
    "syte, sycące, sycace, sycący, sycacy.ß, sycąca, sycaca.ß",
    "vege, wege.ß, vegetarian.ß, wegetariańskie, wegetarianskie, wegetariańska, wegetarianska.ß, bez mięsa, bez miesa, bezmięsne, bezmiesne, bezmięsny, bezmiesny.ß, bezmięsna, bezmiesna.ß",
    "vegan, wegan, wegańskie, weganskie, wegańska, weganska.ß, bez mięsa, bez miesa, bezmięsne, bezmiesne, bezmięsny, bezmiesny.ß, bezmięsna, bezmiesna.ß, bez mleka.ß, bez jaj.ß, bez jajek.ß, bez nabiału, bez nabialu.ß",
    "szybkie, szybki.ß, szybka.ß, błyskawiczne, blyskawiczne, błyskawiczny, blyskawiczny.ß, błyskawiczna, blyskawiczna.ß",
    "tanie, niedrogie.ß, mały koszt, maly koszt",
    "drogie, duży koszt, duzy koszt"
];
